import json
import re
import csv
import os
import torch
from json_repair import repair_json

# ─── Prompt ───────────────────────────────────────────────────────────────────

OPTIMIZATION_PROMPT_TEMPLATE = """
You are Agent 4, a Sustainability-Oriented Metamorphic Test Optimization Agent.

Your job is to prioritize and optimize the metamorphic relations generated by Agent 3.
The goal is to reduce redundant executions while preserving important behavioral coverage.

---

## INPUT
Screen ID: {screen_id}
Topic: {topic}

METAMORPHIC RELATIONS FROM AGENT 3 (columns separated by ::):
{mr_csv}

---

## CORE PRINCIPLE — "Computable Ground Truth" (read this before Step 1)

Not all MR categories carry the same evidentiary weight when they fail, and the
decision tree below is built around ONE governing distinction:

  - A CORRECTNESS-VERIFYING MR has a deterministic, computable expected value
    that the follow-up output must match exactly (e.g. "ratio must increase",
    "converted value must equal 2.54x the original", "still-invalid input must
    still be rejected"). A failure here is an unambiguous logic/computation bug.

  - A BEHAVIOR-STABILITY MR has no computable expected value to check against —
    it only verifies that behavior remains "stable" or "does not break" under a
    small perturbation (e.g. "app should not crash on a repeated tap", "tapping
    icons in reverse order should not corrupt state", "switching tabs and back
    should not lose content"). A failure here signals instability, but there is
    no numeric ground truth being verified.

Only CORRECTNESS-VERIFYING MRs are eligible for "high_priority_keep". This means:
  - VALIDATION_CONSISTENCY   → always correctness-verifying (invalid input must
    deterministically stay invalid) → eligible.
  - MONOTONICITY             → always correctness-verifying (a computed value
    must move in the expected direction) → eligible.
  - INVARIANCE               → ELIGIBLE ONLY when the transformation preserves a
    quantifiable, numeric value (unit/currency/measurement conversion, e.g.
    cm→inch, kg→lb, USD→EUR). NOT eligible when the "invariant" being checked is
    UI state persistence across navigation (e.g. switching tabs/screens and
    back) — that is a behavior-stability check, not a computed-value check,
    even though it shares the INVARIANCE category label.
  - INTERACTION_CONSISTENCY  → NOT eligible. Per its own definition ("similar UI
    interactions should preserve STABLE behavior"), this is a behavior-stability
    check (does end-state stay equivalent regardless of tap order), not a
    computed-value check. It still matters — the first instance per screen is
    "keep" (Step 2) — but it cannot be high_priority_keep.
  - ROBUSTNESS               → NOT eligible. Binary crash/no-crash check, no
    computed expected value.
  - INPUT_TRANSFORMATION     → NOT eligible on its own. It generates a follow-up
    test through a controlled input change but does not itself assert a
    checkable relation; the relation it feeds (typically MONOTONICITY) is what
    gets evaluated for fault-detection criticality.

When you assign "high_priority_keep", your "reason" field MUST name which of the
three eligible cases applies (invalid-input consistency / monotonic computation /
numeric-value-preserving conversion). If an MR does not fit one of those three
cases, it CANNOT be "high_priority_keep" — even if it feels important — it should
be "keep" instead (Step 2).

---

## STANDING EXCEPTIONS (apply these BEFORE and ALONGSIDE the decision tree below —
## they override whatever the tree would otherwise say, in every case)

- VALIDATION_CONSISTENCY MRs on DIFFERENT input fields (age, waist, height,
  email, password, etc.) are NEVER redundant with each other, no matter how
  many there are. Every one of them gets its own "high_priority_keep" — never
  "reduce_repetitions", "partial_sampling", or "lower_priority", regardless
  of how the decision tree below would otherwise classify a repeat.
- MONOTONICITY and INPUT_TRANSFORMATION MRs on DIFFERENT measurable fields
  (e.g. CycleLength vs. PeriodLength) are likewise NEVER redundant with each
  other — each distinct field gets its own full decision from the tree below,
  never automatically downgraded just because another MR shares the category.
- If a category has only ONE MR total in the input, it can never be removed
  or reduced to zero execution — it must land on "keep" or "high_priority_keep"
  (per the Computable Ground Truth principle above — never assign
  "high_priority_keep" here unless the lone MR is itself one of the three
  eligible cases).
- IMPORTANT DATA QUIRK: Agent 3 writes the SAME generic transformation text
  ("Repeat the primary action a second time") for EVERY ROBUSTNESS MR,
  regardless of which UI element it targets. The transformation column being
  identical does NOT mean two ROBUSTNESS MRs are the same element — check
  the follow_up_steps column instead, since that's the only place the actual
  tapped element (icon/button name) appears. A DIFFERENT source_tc_id
  almost always means a DIFFERENT element was tapped, even when the
  transformation text matches exactly — treat these as Step 3
  ("partial_sampling"), NOT Step 4 ("reduce_repetitions"), unless
  follow_up_steps shows the identical element name.

These four exceptions apply to every MR before you walk the tree — check
them FIRST for each MR. If none apply, THEN classify using the tree.

---

## DECISION TREE — walk through each MR and stop at the first step that
## applies. Each step below IS its decision value; there is no separate
## lookup required.

STEP 1 — Does this MR fit ONE of the three eligible cases defined in the
Computable Ground Truth principle above (VALIDATION_CONSISTENCY; MONOTONICITY;
or INVARIANCE that preserves a numeric/quantifiable value, e.g. a unit
conversion — NOT a tab/screen-switch invariance)?
   → YES: decision = "high_priority_keep". These directly catch real
     regressions and must always run first. Name the specific eligible case
     in your reason. STOP HERE.
   → NO: continue to Step 2.

STEP 2 — Is this the FIRST MR of its category on this screen (per the
Standing Exceptions above where applicable), or an important MR that is
not a repeat of anything else (e.g. the first ROBUSTNESS or
INTERACTION_CONSISTENCY check on the screen, a tab-switch INVARIANCE,
an INPUT_TRANSFORMATION not already covered by Step 1)?
   → YES: decision = "keep". Important, run every time. STOP HERE.
   → NO: continue to Step 3.

STEP 3 — Compare this MR's follow_up_steps to the follow_up_steps of an
already-classified MR of the same category. Do they target a DIFFERENT
element (different icon, button, or tab name in follow_up_steps), even if
the transformation column reads identically?
   → YES: decision = "partial_sampling". Same pattern, different target —
     retains some residual value, so sample it occasionally rather than
     cutting it entirely. STOP HERE.
   → NO: continue to Step 4.

STEP 4 — Is this MR a TRUE exact duplicate — does follow_up_steps name the
SAME element as an MR already classified as "keep" or "high_priority_keep"
above (not just matching transformation text)?
   → YES: decision = "reduce_repetitions". No new coverage value; run rarely
     or never. STOP HERE.
   → NO: continue to Step 5.

STEP 5 — None of Steps 1-4 apply. This step is reserved SPECIFICALLY for
MRs whose underlying premise is speculative or domain-dependent — i.e. Agent 3
itself would reasonably mark this MR as lower-confidence (the expected
relation depends on assumptions about app behavior that are not verifiable
from the source test case alone). Do NOT use this step for "same pattern,
different element" — that is Step 3's job, not Step 5's. Only use Step 5 when
the MR's expected relation itself is uncertain, not when its execution
frequency should simply be lower.
   → decision = "lower_priority". Use this whenever an MR genuinely fits
     this specific description — it is not a rare label reserved for edge
     cases, but it is also not a catch-all for "not important."

---

## DECISION VALUES (exact strings — this is what Steps 1-5 above assign)
- "high_priority_keep"  → Step 1: fits one of the three computable-ground-truth
  eligible cases; fault-detection-critical; always run first
- "keep"                → Step 2: important, run every time
- "partial_sampling"    → Step 3: same pattern/different element, sample occasionally
- "reduce_repetitions"  → Step 4: true exact duplicate, run rarely/never
- "lower_priority"      → Step 5: expected relation itself is speculative/domain-dependent

---

## RULES
- Do NOT aggressively delete MRs — prefer downgrading to removing.
- Every mr_id from input must appear in output with a decision.
- Reason must be a short, specific sentence naming which step/exception applied
  (not generic). For "high_priority_keep", name the specific eligible case
  (invalid-input consistency / monotonic computation / numeric-value-preserving
  conversion) per the Computable Ground Truth principle.
- A screen with several distinct-but-related MRs should show a MIX of
  decision values across Steps 1-5 — do not collapse everything into just
  "keep" and "reduce_repetitions".
- Never assign "high_priority_keep" to ROBUSTNESS, INTERACTION_CONSISTENCY,
  INPUT_TRANSFORMATION, or tab/screen-switch INVARIANCE. These categories are
  behavior-stability checks, not computed-value checks, and are structurally
  capped at "keep" even in their most important instance.

---

## OUTPUT
Return ONLY valid JSON, no markdown, no explanation.

{{
  "screen_id": "{screen_id}",
  "optimized_relations": [
    {{
      "mr_id": "MR-01",
      "source_tc_id": "TC_{screen_id}_001",
      "mr_category": "MONOTONICITY",
      "transformation": "...",
      "expected_relation": "...",
      "decision": "high_priority_keep",
      "reason": "Core mathematical behavior — waist increase must raise ratio"
    }}
  ]
}}
"""

# ─── CSV columns ──────────────────────────────────────────────────────────────

OPT_CSV_COLUMNS = [
    "mr_id",
    "source_tc_id",
    "screen_id",
    "topic",
    "mr_category",
    "transformation",
    "expected_relation",
    "decision",
    "reason",
]

# Maps decision value → numeric priority for sorting final output
DECISION_ORDER = {
    "high_priority_keep":  1,
    "keep":                2,
    "partial_sampling":    3,
    "reduce_repetitions":  4,
    "lower_priority":      5,
}

# Categories eligible for "high_priority_keep" under the Computable Ground
# Truth principle. INVARIANCE is included here but is further gated inside
# _is_fault_detection_critical() to only its numeric/quantity-preserving
# subset (unit conversion etc.), NOT tab/screen-switch invariance.
FAULT_CRITICAL_ELIGIBLE_CATEGORIES = {
    "VALIDATION_CONSISTENCY",
    "MONOTONICITY",
    "INVARIANCE",
}

# Keyword set used to detect numeric/quantity-preserving INVARIANCE
# (unit, currency, or measurement conversion) as opposed to UI-state
# persistence invariance (tab/screen switches). This is a heuristic, not a
# semantic parse — documented explicitly here (rather than left as an
# unexplained regex) because it is the operational definition used in the
# paper's methods section for "numeric-value-preserving invariance".
_QUANTITY_CONVERSION_KEYWORDS = (
    "unit", "|", "cm", "inch", "in ", "kg", "lb", "mile", "km",
    "usd", "eur", "gbp", "currency", "celsius", "fahrenheit",
    "convert", "conversion",
)

# Word-boundary regex version of the keyword set above. Plain substring
# matching (kw in transformation) let bare words like "in" match INSIDE
# other words with no boundary — e.g. "Switch away from 'Spin to Win' and
# back" contains "in " twice (inside "Spin" and "Win") and was incorrectly
# promoted to high_priority_keep as if it were a unit conversion. This
# pattern requires the keyword to appear as its own word.
_QUANTITY_CONVERSION_PATTERN = re.compile(
    r"\b(unit|cm|inch|in|kg|lb|mile|km|usd|eur|gbp|currency|"
    r"celsius|fahrenheit|convert|conversion)\b",
    re.IGNORECASE,
)

# Signals that a transformation string follows Agent 3's known ROBUSTNESS
# boilerplate pattern ("Repeat the primary action a second time"), used as
# a defensive check against Agent 3 mislabeling MRs into the wrong
# mr_category (e.g. tagging a robustness repeat as INVARIANCE), which would
# otherwise let that MR wrongly claim a coverage "survivor" slot for a
# category it doesn't actually belong to.
_ROBUSTNESS_PATTERN_HINTS = re.compile(
    r"\b(repeat|repeated|again|second time|retry)\b", re.IGNORECASE
)


# ─── Helpers ──────────────────────────────────────────────────────────────────

def _mr_data_to_csv_string(mr_data: dict) -> str:
    """
    Convert Agent 3 MR dict to a compact CSV string for the prompt. Includes
    follow_up_steps because Agent 3 uses one generic transformation string
    for every ROBUSTNESS repeat ("Repeat the primary action a second time")
    regardless of which UI element it targets — without follow_up_steps,
    Agent 4 has no way to tell "tap the LinkedIn icon twice" apart from
    "tap the Facebook icon twice", since both look identical in every other
    column. follow_up_steps is the only field that actually names the element.
    """
    lines = ["mr_id :: source_tc_id :: mr_category :: transformation :: follow_up_steps :: expected_relation :: confidence"]
    for mr in mr_data.get("metamorphic_relations", []):
        steps = mr.get("follow_up_steps", [])
        steps_str = " | ".join(steps) if isinstance(steps, list) else str(steps)
        lines.append(
            f"{mr.get('mr_id','')} :: {mr.get('source_tc_id','')} :: "
            f"{mr.get('mr_category','')} :: {mr.get('transformation','')} :: "
            f"{steps_str} :: "
            f"{mr.get('expected_relation','')} :: {mr.get('confidence','')}"
        )
    return "\n".join(lines)


def _build_mr_lookup(mr_data: dict) -> dict:
    """Build a dict of mr_id → full MR record for enriching Agent 4 output."""
    return {
        mr.get("mr_id", ""): mr
        for mr in mr_data.get("metamorphic_relations", [])
    }


def _safe_join(val):
    if not val:
        return ""
    if isinstance(val, str):
        return val
    return ", ".join(
        str(v) if not isinstance(v, dict) else json.dumps(v)
        for v in val
    )


def _category_label_is_trustworthy(opt: dict) -> bool:
    """
    Defensive check against Agent 3 mislabeling. Observed in production data:
    Agent 3 sometimes tags a ROBUSTNESS-pattern MR (transformation =
    "Repeat the primary action a second time") with mr_category="INVARIANCE".
    Because the coverage rule below trusts mr_category to find "one survivor
    per (category, source_tc_id)", a mislabeled entry can wrongly claim the
    INVARIANCE survivor slot for that source_tc_id — then the REAL invariance
    MR on the same source_tc_id gets incorrectly flagged as a duplicate and
    demoted to reduce_repetitions, even though it's a completely different,
    legitimate check.

    Returns False when the transformation text looks like the ROBUSTNESS
    boilerplate pattern but the category claims to be something else
    (currently checked for INVARIANCE, the case seen in practice). An MR
    that fails this check is not allowed to occupy a coverage-slot as its
    labeled category in _enforce_coverage_rules.
    """
    cat = opt.get("mr_category", "")
    transformation = opt.get("transformation", "") or ""
    looks_robustness = bool(_ROBUSTNESS_PATTERN_HINTS.search(transformation))
    if cat == "INVARIANCE" and looks_robustness:
        return False
    return True


def _sort_by_decision(optimized: list) -> list:
    """Sort optimized MRs by decision priority (high_priority_keep first)."""
    return sorted(
        optimized,
        key=lambda x: DECISION_ORDER.get(x.get("decision", "lower_priority"), 99),
    )


# ─── Main optimization function ───────────────────────────────────────────────

def optimize_metamorphic_relations(mr_data: dict, model, tokenizer) -> dict:
    """
    Agent 4: takes Agent 3 MR output and returns prioritized/optimized MRs.
    Uses the same Qwen 2.5-7B model as Agents 2 and 3.
    """
    screen_id = mr_data.get("screen_id", "unknown")
    topic     = mr_data.get("topic", "unknown")

    if not mr_data.get("metamorphic_relations"):
        print("   ⚠️  Agent 4: No MRs to optimize — skipping")
        return {"screen_id": screen_id, "topic": topic, "optimized_relations": []}

    mr_csv     = _mr_data_to_csv_string(mr_data)
    mr_lookup  = _build_mr_lookup(mr_data)

    prompt = OPTIMIZATION_PROMPT_TEMPLATE.format(
        screen_id=screen_id,
        topic=topic,
        mr_csv=mr_csv,
    )

    messages = [
        {
            "role": "system",
            "content": (
                "You are a test suite optimization expert. "
                "Output ONLY valid JSON with no markdown or explanation."
            ),
        },
        {"role": "user", "content": prompt},
    ]

    text = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=6144,
    ).to("cuda")

    print(f"   🔄 Optimizing metamorphic relations (Agent 4)...")

    with torch.no_grad():
        ids = model.generate(
            **inputs,
            max_new_tokens=2000,
            do_sample=False,
            top_p=1.0,
            repetition_penalty=1.05,
            pad_token_id=tokenizer.eos_token_id,
        )

    raw = tokenizer.decode(
        ids[0][inputs.input_ids.shape[1]:], skip_special_tokens=True
    )

    try:
        blocks = re.findall(r"\{.*\}", raw, re.DOTALL)
        if not blocks:
            print("   ⚠️  Agent 4: No JSON block found — returning all MRs as 'keep'")
            return _fallback_keep_all(mr_data)

        candidate = max(blocks, key=len)
        repaired  = repair_json(candidate)
        result    = json.loads(repaired)

        optimized = result.get("optimized_relations", [])

        # Enrich with any missing fields from Agent 3 lookup
        for opt in optimized:
            mr_id = opt.get("mr_id", "")
            if mr_id in mr_lookup:
                src = mr_lookup[mr_id]
                opt.setdefault("source_tc_id",   src.get("source_tc_id", ""))
                opt.setdefault("mr_category",     src.get("mr_category", ""))
                opt.setdefault("transformation",  src.get("transformation", ""))
                opt.setdefault("expected_relation", src.get("expected_relation", ""))

        # Validate decision values — fix anything unexpected
        valid_decisions = set(DECISION_ORDER.keys())
        for opt in optimized:
            if opt.get("decision") not in valid_decisions:
                opt["decision"] = "keep"

        optimized = _sort_by_decision(optimized)
        optimized = _enforce_coverage_rules(optimized, mr_data)
        optimized = _upgrade_fault_critical_keeps(optimized)
        optimized = _demote_ineligible_high_priority_keeps(optimized)

        result["optimized_relations"] = optimized
        result["screen_id"] = screen_id
        result["topic"]     = topic

        print(f"   ✅ Agent 4 optimized {len(optimized)} MRs")
        _print_summary(optimized)
        return result

    except Exception as e:
        print(f"   ❌ Agent 4 JSON parse failed: {e} — returning fallback")
        return _fallback_keep_all(mr_data)


def _is_quantity_preserving_invariance(mr: dict) -> bool:
    """
    True only for INVARIANCE MRs that preserve a quantifiable/numeric value
    (unit, currency, or measurement conversion) rather than checking UI-state
    persistence (tab/screen-switch invariance). This is the operational
    definition of "numeric-value-preserving invariance" referenced in the
    Computable Ground Truth principle in OPTIMIZATION_PROMPT_TEMPLATE — kept
    as a single documented keyword list (rather than an ad hoc inline check)
    so the paper's methods section and the code stay in sync.

    This is a heuristic over the transformation text, not a semantic parse,
    and is intentionally conservative: false negatives (missing a real
    conversion MR) fail safe into "keep" rather than "high_priority_keep",
    which matches the "prefer downgrading to removing" rule.
    """
    if mr.get("mr_category", "") != "INVARIANCE":
        return False
    transformation = mr.get("transformation", "") or ""
    return bool(_QUANTITY_CONVERSION_PATTERN.search(transformation)) or "|" in transformation


def _is_fault_detection_critical(mr: dict) -> bool:
    """
    True if this MR fits one of the three Computable Ground Truth eligible
    cases defined in OPTIMIZATION_PROMPT_TEMPLATE, and therefore deserves
    'high_priority_keep' rather than plain 'keep':
      1. VALIDATION_CONSISTENCY — invalid-to-invalid input consistency.
      2. MONOTONICITY — a computed value must move in the expected direction.
      3. INVARIANCE, but ONLY the numeric/quantity-preserving subset (see
         _is_quantity_preserving_invariance) — NOT tab/screen-switch
         invariance, which is a behavior-stability check, not a
         computed-value check.

    All other categories (ROBUSTNESS, INTERACTION_CONSISTENCY,
    INPUT_TRANSFORMATION) are behavior-stability or test-generation
    mechanisms without a computable expected value, and are therefore
    structurally capped at "keep" — see _demote_ineligible_high_priority_keeps
    for the enforcement side of this rule.
    """
    category = mr.get("mr_category", "")

    if category == "VALIDATION_CONSISTENCY":
        return True

    if category == "MONOTONICITY":
        return True

    if category == "INVARIANCE":
        return _is_quantity_preserving_invariance(mr)

    return False


def _upgrade_fault_critical_keeps(optimized: list) -> list:
    """
    Safety net for a gap _enforce_coverage_rules doesn't cover: that function
    only upgrades a decision when RESCUING an MR the LLM demoted to
    reduce_repetitions/partial_sampling/lower_priority. If the LLM's own
    first-pass choice was already "keep" for a fault-detection-critical MR
    (VALIDATION_CONSISTENCY, numeric-value-preserving INVARIANCE,
    MONOTONICITY), nothing previously corrected that "keep" up to
    "high_priority_keep" — it was never treated as needing rescue since
    "keep" isn't a demoted state. This pass catches exactly that case.
    """
    for opt in optimized:
        if opt.get("decision") == "keep" and _is_fault_detection_critical(opt):
            opt["decision"] = "high_priority_keep"
            opt["reason"] = (
                f"Upgraded from 'keep': {opt.get('mr_category','')} is "
                f"fault-detection-critical per the Computable Ground Truth "
                f"principle and must be 'high_priority_keep', not plain 'keep'"
            )
    return optimized


def _demote_ineligible_high_priority_keeps(optimized: list) -> list:
    """
    Hard invariant enforcement: NO MR outside FAULT_CRITICAL_ELIGIBLE_CATEGORIES
    (and, for INVARIANCE, outside its numeric-value-preserving subset) may end
    up as "high_priority_keep" in the final output, regardless of what the LLM
    emitted directly or what any upstream rule assigned.

    This closes a real gap observed empirically: categories such as
    INPUT_TRANSFORMATION (which has no eligibility path in
    _is_fault_detection_critical) were still appearing as "high_priority_keep"
    in production output, meaning the LLM's raw output was reaching the final
    CSV uncapped in at least some cases. Rather than rely solely on the LLM
    following the prompt's rules, this function makes the "only three eligible
    cases" rule a deterministic, code-enforced invariant — required for the
    paper's methods section to accurately describe Agent 4 as a hybrid
    LLM + rule-based system rather than a pure LLM classifier.

    Any MR downgraded here becomes "keep" (never lower) — consistent with the
    "prefer downgrading to removing" rule and with the fact that the MR was
    still judged important enough to survive by whatever upstream logic put
    it here in the first place.
    """
    for opt in optimized:
        if opt.get("decision") != "high_priority_keep":
            continue
        if _is_fault_detection_critical(opt):
            continue
        opt["decision"] = "keep"
        opt["reason"] = (
            f"Fallback mapping — '{opt.get('mr_category','')}' is not one of "
            f"the three Computable Ground Truth eligible categories "
            f"(VALIDATION_CONSISTENCY, MONOTONICITY, numeric-value-preserving "
            f"INVARIANCE); decision clamped from 'high_priority_keep' to 'keep'"
        )
    return optimized


def _enforce_coverage_rules(optimized: list, mr_data: dict) -> list:
    """
    Post-processing safety net that enforces hard rules regardless of model output.

    1. Exactly ONE MR per category survives as the "first instance" baseline —
       every later MR in the same category that Qwen also marked keep/high_priority_keep
       gets capped to reduce_repetitions.

    2. EXCEPTION: categories in NEVER_REDUNDANT_CATEGORIES (VALIDATION_CONSISTENCY,
       INVARIANCE) get the survivor slot applied PER source_tc_id, not once per
       category — because different fields (age/waist/height) or different elements
       (THIS COURSE tab/TOTAL tab) are never true duplicates of each other even
       though they share a category label.

    3. Whenever this function changes a decision, OR finds a decision whose existing
       reason text contradicts it (e.g. decision="keep" but reason says "reduce
       repetitions"), the reason is fully replaced rather than appended to.

    4. When this function is FORCED to make an MR survive (it wasn't already
       keep/high_priority_keep), it checks whether that MR meets the Computable
       Ground Truth criteria (via _is_fault_detection_critical) and assigns
       "high_priority_keep" instead of a flat "keep" when it does. This fixes a
       bug where the coverage rule always defaulted to "keep" even for MRs the
       prompt itself says should be "high_priority_keep" — causing
       high_priority_keep to almost never appear in real output regardless of
       how many boundary/invalid-value/unit-conversion MRs were present. Note
       that the eligibility check itself now excludes tab-switch INVARIANCE and
       INTERACTION_CONSISTENCY (see _is_fault_detection_critical), so this will
       correctly assign "keep" — not "high_priority_keep" — when forcing survival
       of those categories.
    """
    mr_lookup = {mr.get("mr_id", ""): mr for mr in mr_data.get("metamorphic_relations", [])}

    NEVER_REDUNDANT_CATEGORIES = {
        "VALIDATION_CONSISTENCY", "INVARIANCE", "MONOTONICITY", "INPUT_TRANSFORMATION",
    }

    _DEMOTION_LANGUAGE = ("reduce repetition", "redundant", "lower priority", "lower_priority")

    def _sanitize_contradictory_reason(opt: dict, fallback: str) -> None:
        """If decision is keep/high_priority_keep but reason text argues the
        opposite, replace the reason. Safe to call even when nothing changed."""
        reason = (opt.get("reason") or "").lower()
        decision = opt.get("decision", "")
        if decision in ("keep", "high_priority_keep") and any(p in reason for p in _DEMOTION_LANGUAGE):
            opt["reason"] = fallback

    # ── Rule 1: one survivor per category, except NEVER_REDUNDANT_CATEGORIES
    seen_categories = set()
    seen_transformations = {}  # category -> set of transformation strings already accepted as the survivor
    for opt in optimized:
        cat = opt.get("mr_category", "")
        decision = opt.get("decision", "")
        transformation = opt.get("transformation", "")

        if cat in NEVER_REDUNDANT_CATEGORIES:
            continue  # handled per-source_tc_id in Rule 1b below

        if cat not in seen_categories:
            seen_categories.add(cat)
            seen_transformations[cat] = {transformation}
            if decision in ("reduce_repetitions", "partial_sampling", "lower_priority"):
                forced_decision = "high_priority_keep" if _is_fault_detection_critical(opt) else "keep"
                opt["decision"] = forced_decision
                opt["reason"] = f"Coverage rule: first MR of category must survive as '{forced_decision}'"
            else:
                _sanitize_contradictory_reason(
                    opt, "Coverage rule: first MR of category must survive"
                )
            continue

        if decision in ("keep", "high_priority_keep"):
            # A true exact duplicate (same transformation text as an already-
            # accepted survivor in this category) still gets fully cut. A
            # duplicate that targets a different element (different
            # transformation text) retains some residual value and should be
            # sampled occasionally rather than dropped entirely.
            if transformation in seen_transformations[cat]:
                opt["decision"] = "reduce_repetitions"
                opt["reason"] = (
                    f"Coverage rule: exact duplicate {cat} MR on the same screen"
                )
            else:
                opt["decision"] = "partial_sampling"
                opt["reason"] = (
                    f"Coverage rule: only the first {cat} MR per screen is the "
                    f"full baseline; this targets a different element with the "
                    f"same pattern, so it's sampled rather than dropped"
                )
        seen_transformations[cat].add(transformation)

    # ── Rule 1b: NEVER_REDUNDANT_CATEGORIES get one survivor PER source_tc_id,
    # not one per category — different fields/elements are never duplicates.
    seen_per_category_tc: set[tuple] = set()
    for opt in optimized:
        cat = opt.get("mr_category", "")
        if cat not in NEVER_REDUNDANT_CATEGORIES:
            continue

        # Mislabeling guard: if this MR's transformation text looks like
        # Agent 3's ROBUSTNESS boilerplate but it's tagged with a
        # NEVER_REDUNDANT category (e.g. INVARIANCE), don't let it occupy
        # or consume that category's survivor slot for this source_tc_id.
        # It's forced to a safe "keep" on its own, separately, so the real
        # MR of that category on the same source_tc_id isn't wrongly
        # flagged as a duplicate.
        if not _category_label_is_trustworthy(opt):
            decision = opt.get("decision", "")
            if decision not in ("keep", "high_priority_keep"):
                opt["decision"] = "keep"
            opt["reason"] = (
                f"Mislabel guard: transformation text matches the ROBUSTNESS "
                f"boilerplate pattern despite being tagged '{cat}' — kept "
                f"independently without occupying the {cat} coverage slot "
                f"for this source test case, pending an Agent 3 relabel"
            )
            continue

        key = (cat, opt.get("source_tc_id", ""))
        decision = opt.get("decision", "")

        if key not in seen_per_category_tc:
            seen_per_category_tc.add(key)
            if decision in ("reduce_repetitions", "partial_sampling", "lower_priority"):
                forced_decision = "high_priority_keep" if _is_fault_detection_critical(opt) else "keep"
                opt["decision"] = forced_decision
                opt["reason"] = f"{cat} on a distinct source test case — never redundant, must be kept as '{forced_decision}'"
            else:
                _sanitize_contradictory_reason(
                    opt, f"{cat} on a distinct source test case — never redundant, must be kept"
                )
        else:
            # True duplicate: same category AND same source_tc_id seen before.
            if decision in ("keep", "high_priority_keep"):
                opt["decision"] = "reduce_repetitions"
                opt["reason"] = (
                    f"Coverage rule: duplicate {cat} MR on the same source test case"
                )

    return optimized

def _fallback_keep_all(mr_data: dict) -> dict:
    """If Agent 4 fails to parse, keep all MRs with decision='keep'."""
    screen_id = mr_data.get("screen_id", "unknown")
    topic     = mr_data.get("topic", "unknown")
    optimized = []
    for mr in mr_data.get("metamorphic_relations", []):
        optimized.append({
            "mr_id":             mr.get("mr_id", ""),
            "source_tc_id":      mr.get("source_tc_id", ""),
            "mr_category":       mr.get("mr_category", ""),
            "transformation":    mr.get("transformation", ""),
            "expected_relation": mr.get("expected_relation", ""),
            "decision":          "keep",
            "reason":            "Fallback — Agent 4 parse failed",
        })
    return {"screen_id": screen_id, "topic": topic, "optimized_relations": optimized}


def _print_summary(optimized: list):
    """Print a compact decision summary to console."""
    from collections import Counter
    counts = Counter(opt.get("decision", "") for opt in optimized)
    summary = " | ".join(f"{d}: {n}" for d, n in sorted(counts.items()))
    print(f"   📊 Decision summary — {summary}")


# ─── Save functions ───────────────────────────────────────────────────────────

def save_optimized_mr_data(
    opt_data: dict,
    out_dir: str = "outputs/optimized_relations",
):
    """Save optimized MRs to individual CSV per screen (e.g. 124_Prioritize_MR.csv)."""
    os.makedirs(out_dir, exist_ok=True)
    screen_id = opt_data.get("screen_id", "unknown")
    topic     = opt_data.get("topic", "unknown")
    optimized = opt_data.get("optimized_relations", [])

    out_path = os.path.join(out_dir, f"{screen_id}_Prioritize_MR.csv")
    if os.path.exists(out_path):
        os.remove(out_path)

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=OPT_CSV_COLUMNS)
        w.writeheader()
        for opt in optimized:
            w.writerow({
                "mr_id":             opt.get("mr_id", ""),
                "source_tc_id":      opt.get("source_tc_id", ""),
                "screen_id":         screen_id,
                "topic":             topic,
                "mr_category":       opt.get("mr_category", ""),
                "transformation":    opt.get("transformation", ""),
                "expected_relation": opt.get("expected_relation", ""),
                "decision":          opt.get("decision", ""),
                "reason":            opt.get("reason", ""),
            })

    print(f"  💾 Optimized MRs saved → {out_path}")
    return out_path


def append_optimized_mr_to_master(
    opt_data: dict,
    master_path: str = "outputs/optimized_relations_master.csv",
):
    """Append optimized MRs to master CSV."""
    os.makedirs(os.path.dirname(master_path), exist_ok=True)
    screen_id = opt_data.get("screen_id", "unknown")
    topic     = opt_data.get("topic", "unknown")
    optimized = opt_data.get("optimized_relations", [])

    exists = os.path.exists(master_path)
    with open(master_path, "a", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=OPT_CSV_COLUMNS)
        if not exists:
            w.writeheader()
        for opt in optimized:
            w.writerow({
                "mr_id":             opt.get("mr_id", ""),
                "source_tc_id":      opt.get("source_tc_id", ""),
                "screen_id":         screen_id,
                "topic":             topic,
                "mr_category":       opt.get("mr_category", ""),
                "transformation":    opt.get("transformation", ""),
                "expected_relation": opt.get("expected_relation", ""),
                "decision":          opt.get("decision", ""),
                "reason":            opt.get("reason", ""),
            })

    print(f"  💾 Optimized MRs appended to master → {master_path}")